def risk_graphql(created: int,
                 charge: str):
    return {"operationName": "RadarAllSignalsForChargeQuery",
            "variables": {"time": created, "input": {"charge": f'"{charge}"'}},
            "query": "query RadarAllSignalsForChargeQuery($time: Int!, $input: ApiRadarSignalsSignalsDataInput) "
                     "{\n  currentMerchant {\n    id\n    created\n    radarSettingsAtTime(time: $time) {\n     "
                     " highestRiskThreshold\n      elevatedRiskThreshold\n      __typename\n    }\n    "
                     "__typename\n  }\n  radarSignalsData(input: $input) {\n    amountMeanForCard\n    "
                     "amountStandardDeviationForCard\n    billingToIpDistanceInKm\n    "
                     "shippingToBillingDistanceInKm\n    shippingToIpDistanceInKm\n    amountInUsd\n    "
                     "issuingBank\n    email\n    cardName\n    deviceBrand\n    deviceModel\n    emailAge\n    "
                     "internetServiceProvidor\n    cardholderIp\n    operatingSystem\n    browser\n    "
                     "cardholderName\n    cardCountsForDeviceLastWeek {\n      counterValue\n      insightsData "
                     "{\n        ...CounterFeatureInsightsDataFragment\n        __typename\n      }\n      "
                     "selectedBucket\n      __typename\n    }\n    cardCountsForDeviceSecondsSinceFirstSeen {\n "
                     "     counterValue\n      insightsData {\n        ...CounterFeatureInsightsDataFragment\n  "
                     "      __typename\n      }\n      selectedBucket\n      __typename\n    }\n    "
                     "cardCountsForEmailDeclinesLastWeek {\n      counterValue\n      insightsData {\n        "
                     "...CounterFeatureInsightsDataFragment\n        __typename\n      }\n      "
                     "selectedBucket\n      __typename\n    }\n    "
                     "cardCountsForEmailDeclinesSecondsSinceFirstSeen {\n      counterValue\n      insightsData "
                     "{\n        ...CounterFeatureInsightsDataFragment\n        __typename\n      }\n      "
                     "selectedBucket\n      __typename\n    }\n    cardCountsForIpLastWeek {\n      "
                     "counterValue\n      insightsData {\n        ...CounterFeatureInsightsDataFragment\n       "
                     " __typename\n      }\n      selectedBucket\n      __typename\n    }\n    "
                     "chargesForIpAllTimeSuccessRate {\n      counterValue\n      insightsData {\n        "
                     "...CounterFeatureInsightsDataFragment\n        __typename\n      }\n      "
                     "selectedBucket\n      __typename\n    }\n    ipCountsForCardAuthorizedLastWeek {\n      "
                     "counterValue\n      insightsData {\n        ...CounterFeatureInsightsDataFragment\n       "
                     " __typename\n      }\n      selectedBucket\n      __typename\n    }\n    "
                     "ipCountsForCardAuthorizedSecondsSinceFirstSeen {\n      counterValue\n      insightsData "
                     "{\n        ...CounterFeatureInsightsDataFragment\n        __typename\n      }\n      "
                     "selectedBucket\n      __typename\n    }\n    nameCountsForIpLastWeek {\n      "
                     "counterValue\n      insightsData {\n        ...CounterFeatureInsightsDataFragment\n       "
                     " __typename\n      }\n      selectedBucket\n      __typename\n    }\n    "
                     "nameCountsForIpSecondsSinceFirstSeen {\n      counterValue\n      insightsData {\n        "
                     "...CounterFeatureInsightsDataFragment\n        __typename\n      }\n      "
                     "selectedBucket\n      __typename\n    }\n    normalizedNameCountsForCardLastWeek {\n      "
                     "counterValue\n      insightsData {\n        ...CounterFeatureInsightsDataFragment\n       "
                     " __typename\n      }\n      selectedBucket\n      __typename\n    }\n    "
                     "countryCountsForCardLastWeek {\n      counterValue\n      insightsData {\n        "
                     "...CounterFeatureInsightsDataFragment\n        __typename\n      }\n      "
                     "selectedBucket\n      __typename\n    }\n    chargesForEmailAllTimeSuccessRate {\n      "
                     "counterValue\n      insightsData {\n        ...CounterFeatureInsightsDataFragment\n       "
                     " __typename\n      }\n      selectedBucket\n      __typename\n    }\n    isDebit {\n      "
                     "value\n      insightsData {\n        ...CategoricalFeatureInsightsDataFragment\n        "
                     "__typename\n      }\n      __typename\n    }\n    isPrepaid {\n      value\n      "
                     "insightsData {\n        ...CategoricalFeatureInsightsDataFragment\n        __typename\n   "
                     "   }\n      __typename\n    }\n    pastedCvc {\n      value\n      insightsData {\n       "
                     " ...CategoricalFeatureInsightsDataFragment\n        __typename\n      }\n      "
                     "__typename\n    }\n    pastedEmail {\n      value\n      insightsData {\n        "
                     "...CategoricalFeatureInsightsDataFragment\n        __typename\n      }\n      "
                     "__typename\n    }\n    pastedExpiration {\n      value\n      insightsData {\n        "
                     "...CategoricalFeatureInsightsDataFragment\n        __typename\n      }\n      "
                     "__typename\n    }\n    pastedNumber {\n      value\n      insightsData {\n        "
                     "...CategoricalFeatureInsightsDataFragment\n        __typename\n      }\n      "
                     "__typename\n    }\n    pastedZip {\n      value\n      insightsData {\n        "
                     "...CategoricalFeatureInsightsDataFragment\n        __typename\n      }\n      "
                     "__typename\n    }\n    isNamePartInEmail {\n      value\n      insightsData {\n        "
                     "...CategoricalFeatureInsightsDataFragment\n        __typename\n      }\n      "
                     "__typename\n    }\n    hasPriorDisputeOnCardholderIp {\n      value\n      insightsData {"
                     "\n        ...CategoricalFeatureInsightsDataFragment\n        __typename\n      }\n      "
                     "__typename\n    }\n    hasPriorIfrOnCardholderIp {\n      value\n      insightsData {\n   "
                     "     ...CategoricalFeatureInsightsDataFragment\n        __typename\n      }\n      "
                     "__typename\n    }\n    __typename\n  }\n}\n\nfragment CounterFeatureInsightsDataFragment "
                     "on ApiRadarSignalsCounterSignalBucket {\n  key\n  networkDistribution\n  "
                     "normalizedFraudRate\n  __typename\n}\n\nfragment CategoricalFeatureInsightsDataFragment "
                     "on ApiRadarSignalsCategoricalSignalBucket {\n  bucketValue\n  networkDistribution\n  "
                     "normalizedFraudRate\n  __typename\n}\n"}
